// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Internal representations for operations.
type Op int32

const (
	Op_GET   Op = 0
	Op_SET   Op = 1
	Op_CLEAR Op = 2
	Op_CAS   Op = 3
)

var Op_name = map[int32]string{
	0: "GET",
	1: "SET",
	2: "CLEAR",
	3: "CAS",
}

var Op_value = map[string]int32{
	"GET":   0,
	"SET":   1,
	"CLEAR": 2,
	"CAS":   3,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

// Represents a single key, used for gets.
type Key struct {
	Key                  string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Signature            *ClientSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Key) GetSignature() *ClientSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Represents a single value, can be used for put etc.
type Value struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Represent a key-value pair that is used to return results.
type KeyValue struct {
	Key                  string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Signature            *ClientSignature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KeyValue) GetSignature() *ClientSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Represent a void message indicating success
type Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{3}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

// Represents an error.
type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// Represents an argument for CAS
type CASArg struct {
	Kv                   *KeyValue        `protobuf:"bytes,1,opt,name=kv,proto3" json:"kv,omitempty"`
	Value                *Value           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Signature            *ClientSignature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CASArg) Reset()         { *m = CASArg{} }
func (m *CASArg) String() string { return proto.CompactTextString(m) }
func (*CASArg) ProtoMessage()    {}
func (*CASArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{5}
}

func (m *CASArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CASArg.Unmarshal(m, b)
}
func (m *CASArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CASArg.Marshal(b, m, deterministic)
}
func (m *CASArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CASArg.Merge(m, src)
}
func (m *CASArg) XXX_Size() int {
	return xxx_messageInfo_CASArg.Size(m)
}
func (m *CASArg) XXX_DiscardUnknown() {
	xxx_messageInfo_CASArg.DiscardUnknown(m)
}

var xxx_messageInfo_CASArg proto.InternalMessageInfo

func (m *CASArg) GetKv() *KeyValue {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *CASArg) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CASArg) GetSignature() *ClientSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Represents an empty message
type Empty struct {
	Signature            *ClientSignature `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (m *Empty) GetSignature() *ClientSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Represents a case where we need the client to connect
// to another server.
type Redirect struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{7}
}

func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (m *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(m, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

// Represents an operation result.
type Result struct {
	// Types that are valid to be assigned to Result:
	//	*Result_Redirect
	//	*Result_Kv
	//	*Result_S
	Result               isResult_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{8}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type isResult_Result interface {
	isResult_Result()
}

type Result_Redirect struct {
	Redirect *Redirect `protobuf:"bytes,1,opt,name=redirect,proto3,oneof"`
}

type Result_Kv struct {
	Kv *KeyValue `protobuf:"bytes,2,opt,name=kv,proto3,oneof"`
}

type Result_S struct {
	S *Success `protobuf:"bytes,3,opt,name=s,proto3,oneof"`
}

func (*Result_Redirect) isResult_Result() {}

func (*Result_Kv) isResult_Result() {}

func (*Result_S) isResult_Result() {}

func (m *Result) GetResult() isResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Result) GetRedirect() *Redirect {
	if x, ok := m.GetResult().(*Result_Redirect); ok {
		return x.Redirect
	}
	return nil
}

func (m *Result) GetKv() *KeyValue {
	if x, ok := m.GetResult().(*Result_Kv); ok {
		return x.Kv
	}
	return nil
}

func (m *Result) GetS() *Success {
	if x, ok := m.GetResult().(*Result_S); ok {
		return x.S
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Result) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Result_OneofMarshaler, _Result_OneofUnmarshaler, _Result_OneofSizer, []interface{}{
		(*Result_Redirect)(nil),
		(*Result_Kv)(nil),
		(*Result_S)(nil),
	}
}

func _Result_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Result)
	// result
	switch x := m.Result.(type) {
	case *Result_Redirect:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Redirect); err != nil {
			return err
		}
	case *Result_Kv:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Kv); err != nil {
			return err
		}
	case *Result_S:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.S); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Result.Result has unexpected type %T", x)
	}
	return nil
}

func _Result_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Result)
	switch tag {
	case 1: // result.redirect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Redirect)
		err := b.DecodeMessage(msg)
		m.Result = &Result_Redirect{msg}
		return true, err
	case 2: // result.kv
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KeyValue)
		err := b.DecodeMessage(msg)
		m.Result = &Result_Kv{msg}
		return true, err
	case 3: // result.s
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Success)
		err := b.DecodeMessage(msg)
		m.Result = &Result_S{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Result_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Result)
	// result
	switch x := m.Result.(type) {
	case *Result_Redirect:
		s := proto.Size(x.Redirect)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Result_Kv:
		s := proto.Size(x.Kv)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Result_S:
		s := proto.Size(x.S)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A type for arguments across all operations
type Command struct {
	Operation Op `protobuf:"varint,1,opt,name=operation,proto3,enum=pb.Op" json:"operation,omitempty"`
	// Types that are valid to be assigned to Arg:
	//	*Command_Get
	//	*Command_Set
	//	*Command_Clear
	//	*Command_Cas
	Arg                  isCommand_Arg `protobuf_oneof:"arg"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{9}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetOperation() Op {
	if m != nil {
		return m.Operation
	}
	return Op_GET
}

type isCommand_Arg interface {
	isCommand_Arg()
}

type Command_Get struct {
	Get *Key `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

type Command_Set struct {
	Set *KeyValue `protobuf:"bytes,3,opt,name=set,proto3,oneof"`
}

type Command_Clear struct {
	Clear *Empty `protobuf:"bytes,4,opt,name=clear,proto3,oneof"`
}

type Command_Cas struct {
	Cas *CASArg `protobuf:"bytes,5,opt,name=cas,proto3,oneof"`
}

func (*Command_Get) isCommand_Arg() {}

func (*Command_Set) isCommand_Arg() {}

func (*Command_Clear) isCommand_Arg() {}

func (*Command_Cas) isCommand_Arg() {}

func (m *Command) GetArg() isCommand_Arg {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (m *Command) GetGet() *Key {
	if x, ok := m.GetArg().(*Command_Get); ok {
		return x.Get
	}
	return nil
}

func (m *Command) GetSet() *KeyValue {
	if x, ok := m.GetArg().(*Command_Set); ok {
		return x.Set
	}
	return nil
}

func (m *Command) GetClear() *Empty {
	if x, ok := m.GetArg().(*Command_Clear); ok {
		return x.Clear
	}
	return nil
}

func (m *Command) GetCas() *CASArg {
	if x, ok := m.GetArg().(*Command_Cas); ok {
		return x.Cas
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Command) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Command_OneofMarshaler, _Command_OneofUnmarshaler, _Command_OneofSizer, []interface{}{
		(*Command_Get)(nil),
		(*Command_Set)(nil),
		(*Command_Clear)(nil),
		(*Command_Cas)(nil),
	}
}

func _Command_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Command)
	// arg
	switch x := m.Arg.(type) {
	case *Command_Get:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Get); err != nil {
			return err
		}
	case *Command_Set:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Set); err != nil {
			return err
		}
	case *Command_Clear:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Clear); err != nil {
			return err
		}
	case *Command_Cas:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cas); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Command.Arg has unexpected type %T", x)
	}
	return nil
}

func _Command_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Command)
	switch tag {
	case 2: // arg.get
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Key)
		err := b.DecodeMessage(msg)
		m.Arg = &Command_Get{msg}
		return true, err
	case 3: // arg.set
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(KeyValue)
		err := b.DecodeMessage(msg)
		m.Arg = &Command_Set{msg}
		return true, err
	case 4: // arg.clear
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Empty)
		err := b.DecodeMessage(msg)
		m.Arg = &Command_Clear{msg}
		return true, err
	case 5: // arg.cas
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CASArg)
		err := b.DecodeMessage(msg)
		m.Arg = &Command_Cas{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Command_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Command)
	// arg
	switch x := m.Arg.(type) {
	case *Command_Get:
		s := proto.Size(x.Get)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_Set:
		s := proto.Size(x.Set)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_Clear:
		s := proto.Size(x.Clear)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_Cas:
		s := proto.Size(x.Cas)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A log entry
type Entry struct {
	Term                 int64            `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index                int64            `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Cmd                  *Command         `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Signature            *ClientSignature `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{10}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Entry) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *Entry) GetSignature() *ClientSignature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Signed Vote entry
type Vote struct {
	Peer                 string     `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Term                 int64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Signature            *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{11}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *Vote) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Vote) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Input to AppendEntries
type AppendEntriesArgs struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderID             string   `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	PrevLogIndex         int64    `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogHash          int64    `protobuf:"varint,4,opt,name=prevLogHash,proto3" json:"prevLogHash,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	Votes                []*Vote  `protobuf:"bytes,6,rep,name=votes,proto3" json:"votes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesArgs) Reset()         { *m = AppendEntriesArgs{} }
func (m *AppendEntriesArgs) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesArgs) ProtoMessage()    {}
func (*AppendEntriesArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{12}
}

func (m *AppendEntriesArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesArgs.Unmarshal(m, b)
}
func (m *AppendEntriesArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesArgs.Marshal(b, m, deterministic)
}
func (m *AppendEntriesArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesArgs.Merge(m, src)
}
func (m *AppendEntriesArgs) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesArgs.Size(m)
}
func (m *AppendEntriesArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesArgs proto.InternalMessageInfo

func (m *AppendEntriesArgs) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesArgs) GetLeaderID() string {
	if m != nil {
		return m.LeaderID
	}
	return ""
}

func (m *AppendEntriesArgs) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesArgs) GetPrevLogHash() int64 {
	if m != nil {
		return m.PrevLogHash
	}
	return 0
}

func (m *AppendEntriesArgs) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesArgs) GetVotes() []*Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

// Output from AppendEntries
type AppendEntriesRet struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	NeedProof            bool     `protobuf:"varint,3,opt,name=needProof,proto3" json:"needProof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesRet) Reset()         { *m = AppendEntriesRet{} }
func (m *AppendEntriesRet) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRet) ProtoMessage()    {}
func (*AppendEntriesRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{13}
}

func (m *AppendEntriesRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRet.Unmarshal(m, b)
}
func (m *AppendEntriesRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRet.Marshal(b, m, deterministic)
}
func (m *AppendEntriesRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRet.Merge(m, src)
}
func (m *AppendEntriesRet) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRet.Size(m)
}
func (m *AppendEntriesRet) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRet.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRet proto.InternalMessageInfo

func (m *AppendEntriesRet) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRet) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesRet) GetNeedProof() bool {
	if m != nil {
		return m.NeedProof
	}
	return false
}

// Input to RequestVote
type RequestVoteArgs struct {
	Term                 int64                `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateID          string               `protobuf:"bytes,2,opt,name=candidateID,proto3" json:"candidateID,omitempty"`
	LastLogIndex         int64                `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LasLogTerm           int64                `protobuf:"varint,4,opt,name=lasLogTerm,proto3" json:"lasLogTerm,omitempty"`
	Proof                []*LeaderChangeProof `protobuf:"bytes,5,rep,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestVoteArgs) Reset()         { *m = RequestVoteArgs{} }
func (m *RequestVoteArgs) String() string { return proto.CompactTextString(m) }
func (*RequestVoteArgs) ProtoMessage()    {}
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{14}
}

func (m *RequestVoteArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteArgs.Unmarshal(m, b)
}
func (m *RequestVoteArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteArgs.Marshal(b, m, deterministic)
}
func (m *RequestVoteArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteArgs.Merge(m, src)
}
func (m *RequestVoteArgs) XXX_Size() int {
	return xxx_messageInfo_RequestVoteArgs.Size(m)
}
func (m *RequestVoteArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteArgs.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteArgs proto.InternalMessageInfo

func (m *RequestVoteArgs) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteArgs) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

func (m *RequestVoteArgs) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteArgs) GetLasLogTerm() int64 {
	if m != nil {
		return m.LasLogTerm
	}
	return 0
}

func (m *RequestVoteArgs) GetProof() []*LeaderChangeProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

// Output from RequestVote
type RequestVoteRet struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          bool     `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	SignedVote           *Vote    `protobuf:"bytes,3,opt,name=signedVote,proto3" json:"signedVote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRet) Reset()         { *m = RequestVoteRet{} }
func (m *RequestVoteRet) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRet) ProtoMessage()    {}
func (*RequestVoteRet) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{15}
}

func (m *RequestVoteRet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRet.Unmarshal(m, b)
}
func (m *RequestVoteRet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRet.Marshal(b, m, deterministic)
}
func (m *RequestVoteRet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRet.Merge(m, src)
}
func (m *RequestVoteRet) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRet.Size(m)
}
func (m *RequestVoteRet) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRet.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRet proto.InternalMessageInfo

func (m *RequestVoteRet) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRet) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

func (m *RequestVoteRet) GetSignedVote() *Vote {
	if m != nil {
		return m.SignedVote
	}
	return nil
}

// Proof for Leader Change request
type LeaderChangeProof struct {
	Peer                 string     `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Term                 int64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Signature            *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LeaderChangeProof) Reset()         { *m = LeaderChangeProof{} }
func (m *LeaderChangeProof) String() string { return proto.CompactTextString(m) }
func (*LeaderChangeProof) ProtoMessage()    {}
func (*LeaderChangeProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{16}
}

func (m *LeaderChangeProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderChangeProof.Unmarshal(m, b)
}
func (m *LeaderChangeProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderChangeProof.Marshal(b, m, deterministic)
}
func (m *LeaderChangeProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderChangeProof.Merge(m, src)
}
func (m *LeaderChangeProof) XXX_Size() int {
	return xxx_messageInfo_LeaderChangeProof.Size(m)
}
func (m *LeaderChangeProof) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderChangeProof.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderChangeProof proto.InternalMessageInfo

func (m *LeaderChangeProof) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *LeaderChangeProof) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LeaderChangeProof) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Input to AppendEntriesRes
type AppendEntriesResArgs struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Hash                 int64    `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntriesResArgs) Reset()         { *m = AppendEntriesResArgs{} }
func (m *AppendEntriesResArgs) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesResArgs) ProtoMessage()    {}
func (*AppendEntriesResArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{17}
}

func (m *AppendEntriesResArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesResArgs.Unmarshal(m, b)
}
func (m *AppendEntriesResArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesResArgs.Marshal(b, m, deterministic)
}
func (m *AppendEntriesResArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesResArgs.Merge(m, src)
}
func (m *AppendEntriesResArgs) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesResArgs.Size(m)
}
func (m *AppendEntriesResArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesResArgs.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesResArgs proto.InternalMessageInfo

func (m *AppendEntriesResArgs) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *AppendEntriesResArgs) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *AppendEntriesResArgs) GetHash() int64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

// Signature
type Signature struct {
	R                    int64    `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	S                    int64    `protobuf:"varint,2,opt,name=s,proto3" json:"s,omitempty"`
	SignHash             []byte   `protobuf:"bytes,3,opt,name=signHash,proto3" json:"signHash,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{18}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetR() int64 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *Signature) GetS() int64 {
	if m != nil {
		return m.S
	}
	return 0
}

func (m *Signature) GetSignHash() []byte {
	if m != nil {
		return m.SignHash
	}
	return nil
}

func (m *Signature) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

// Client signatures
type ClientSignature struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature            *Signature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ClientSignature) Reset()         { *m = ClientSignature{} }
func (m *ClientSignature) String() string { return proto.CompactTextString(m) }
func (*ClientSignature) ProtoMessage()    {}
func (*ClientSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{19}
}

func (m *ClientSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSignature.Unmarshal(m, b)
}
func (m *ClientSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSignature.Marshal(b, m, deterministic)
}
func (m *ClientSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSignature.Merge(m, src)
}
func (m *ClientSignature) XXX_Size() int {
	return xxx_messageInfo_ClientSignature.Size(m)
}
func (m *ClientSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSignature.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSignature proto.InternalMessageInfo

func (m *ClientSignature) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientSignature) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Empty message
type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{20}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pb.Op", Op_name, Op_value)
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*Value)(nil), "pb.Value")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterType((*Success)(nil), "pb.Success")
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*CASArg)(nil), "pb.CASArg")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Redirect)(nil), "pb.Redirect")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*Command)(nil), "pb.Command")
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*Vote)(nil), "pb.Vote")
	proto.RegisterType((*AppendEntriesArgs)(nil), "pb.AppendEntriesArgs")
	proto.RegisterType((*AppendEntriesRet)(nil), "pb.AppendEntriesRet")
	proto.RegisterType((*RequestVoteArgs)(nil), "pb.RequestVoteArgs")
	proto.RegisterType((*RequestVoteRet)(nil), "pb.RequestVoteRet")
	proto.RegisterType((*LeaderChangeProof)(nil), "pb.LeaderChangeProof")
	proto.RegisterType((*AppendEntriesResArgs)(nil), "pb.AppendEntriesResArgs")
	proto.RegisterType((*Signature)(nil), "pb.Signature")
	proto.RegisterType((*ClientSignature)(nil), "pb.ClientSignature")
	proto.RegisterType((*Void)(nil), "pb.Void")
}

func init() { proto.RegisterFile("kv.proto", fileDescriptor_2216fe83c9c12408) }

var fileDescriptor_2216fe83c9c12408 = []byte{
	// 976 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe2, 0xc6,
	0x17, 0xc7, 0x36, 0xe6, 0xe3, 0xc0, 0x66, 0xd9, 0x93, 0xfc, 0xff, 0xa2, 0x6c, 0x36, 0xcb, 0xba,
	0xbd, 0x88, 0xb2, 0x52, 0xa4, 0xd2, 0x9b, 0xaa, 0x17, 0x95, 0x58, 0x8a, 0xc2, 0x36, 0x51, 0xb7,
	0x1a, 0xa2, 0xbd, 0xa9, 0x54, 0xc9, 0xc1, 0x67, 0x1d, 0x2b, 0x60, 0xbb, 0x33, 0x03, 0x2a, 0xed,
	0x65, 0xaf, 0xfb, 0x3e, 0x7d, 0x8a, 0x3e, 0x4d, 0x1f, 0xa0, 0x9a, 0xf1, 0x60, 0x8c, 0x61, 0xd5,
	0xa8, 0x52, 0xef, 0x3c, 0xe7, 0xf3, 0x77, 0x7e, 0xe7, 0x03, 0xa0, 0xf1, 0xb0, 0xba, 0x4c, 0x79,
	0x22, 0x13, 0xb4, 0xd3, 0x3b, 0xef, 0x5b, 0x70, 0xae, 0x69, 0x8d, 0x1d, 0x70, 0x1e, 0x68, 0xdd,
	0xb5, 0xfa, 0xd6, 0x79, 0x93, 0xa9, 0x4f, 0xfc, 0x1c, 0x9a, 0x22, 0x0a, 0x63, 0x5f, 0x2e, 0x39,
	0x75, 0xed, 0xbe, 0x75, 0xde, 0x1a, 0x1c, 0x5f, 0xa6, 0x77, 0x97, 0xa3, 0x79, 0x44, 0xb1, 0x9c,
	0x6e, 0x54, 0x6c, 0x6b, 0xe5, 0xbd, 0x00, 0xf7, 0xbd, 0x3f, 0x5f, 0x12, 0x9e, 0x80, 0xbb, 0x52,
	0x1f, 0x26, 0x5e, 0xf6, 0xf0, 0x08, 0x1a, 0xd7, 0xb4, 0xce, 0x2c, 0xf6, 0xf3, 0xe5, 0x3e, 0x76,
	0xc1, 0x67, 0x17, 0x85, 0xf3, 0x28, 0x14, 0x4d, 0xa8, 0x4f, 0x97, 0xb3, 0x19, 0x09, 0xe1, 0x7d,
	0x02, 0xee, 0x98, 0xf3, 0x84, 0xab, 0x74, 0x0b, 0x11, 0x6e, 0xd2, 0x2d, 0x44, 0xe8, 0xfd, 0x02,
	0xb5, 0xd1, 0x70, 0x3a, 0xe4, 0x21, 0x9e, 0x82, 0xfd, 0xb0, 0xd2, 0xaa, 0xd6, 0xa0, 0xad, 0x62,
	0x6f, 0x40, 0x32, 0xfb, 0x61, 0x85, 0x2f, 0x8b, 0xb0, 0x5a, 0x83, 0xa6, 0x32, 0xc8, 0xb4, 0xff,
	0x1e, 0xe1, 0x57, 0xe0, 0x8e, 0x17, 0xa9, 0x2c, 0x71, 0x6c, 0x3d, 0xca, 0xd7, 0x83, 0x06, 0xa3,
	0x20, 0xe2, 0x34, 0x93, 0xf8, 0x7f, 0xa8, 0x09, 0xe2, 0x2b, 0xe2, 0xa6, 0x30, 0xf3, 0xf2, 0x7e,
	0x85, 0x1a, 0x23, 0xb1, 0x9c, 0x4b, 0xbc, 0x80, 0x06, 0x37, 0xd6, 0xc5, 0x0a, 0x37, 0x11, 0x26,
	0x15, 0x96, 0xeb, 0xf1, 0x4c, 0xf3, 0x60, 0xef, 0xf3, 0x30, 0xa9, 0x68, 0x26, 0x9e, 0x83, 0x25,
	0x4c, 0x81, 0x2d, 0xa5, 0x36, 0x24, 0x4f, 0x2a, 0xcc, 0x12, 0x6f, 0x1a, 0x50, 0xe3, 0x3a, 0xa5,
	0xf7, 0x87, 0x05, 0xf5, 0x51, 0xb2, 0x58, 0xf8, 0x71, 0x80, 0x9f, 0x41, 0x33, 0x49, 0x89, 0xfb,
	0x32, 0x4a, 0x62, 0x9d, 0xff, 0x68, 0x50, 0x53, 0xae, 0xef, 0x52, 0xb6, 0x55, 0xe0, 0x73, 0x70,
	0x42, 0x92, 0x26, 0x73, 0xdd, 0x64, 0x9e, 0x54, 0x98, 0x92, 0x62, 0x1f, 0x1c, 0x41, 0xd2, 0xe4,
	0x2d, 0xc3, 0x52, 0x2a, 0x7c, 0x05, 0xee, 0x6c, 0x4e, 0x3e, 0xef, 0x56, 0xb7, 0x1d, 0xd2, 0xf4,
	0x4e, 0x2a, 0x2c, 0xd3, 0xe0, 0x19, 0x38, 0x33, 0x5f, 0x74, 0x5d, 0x6d, 0x00, 0x9a, 0x61, 0xdd,
	0x7b, 0x15, 0x62, 0xe6, 0x8b, 0x37, 0x2e, 0x38, 0x3e, 0x0f, 0xbd, 0xdf, 0x2c, 0x70, 0xc7, 0xb1,
	0xe4, 0x6b, 0x44, 0xa8, 0x4a, 0xe2, 0x0b, 0x8d, 0xd9, 0x61, 0xfa, 0x5b, 0x0d, 0x68, 0x14, 0x07,
	0xf4, 0xb3, 0x06, 0xea, 0xb0, 0xec, 0x81, 0x2f, 0xc0, 0x99, 0x2d, 0x82, 0x22, 0x2f, 0xa6, 0x78,
	0xa6, 0xe4, 0xbb, 0x1d, 0xae, 0x3e, 0xaa, 0xc3, 0x3f, 0x40, 0xf5, 0x7d, 0x22, 0x49, 0x61, 0x48,
	0x29, 0xef, 0xad, 0xfe, 0xce, 0x71, 0xd9, 0x05, 0x5c, 0xaf, 0xf7, 0x07, 0xf0, 0x89, 0xee, 0xcf,
	0xa1, 0xe0, 0x7f, 0x5a, 0xf0, 0x6c, 0x98, 0xa6, 0x14, 0x07, 0xaa, 0xd0, 0x88, 0xc4, 0x90, 0x87,
	0xe2, 0x60, 0xb9, 0x3d, 0x68, 0xcc, 0xc9, 0x0f, 0x88, 0xbf, 0xfd, 0xc6, 0xac, 0x64, 0xfe, 0x46,
	0x0f, 0xda, 0x29, 0xa7, 0xd5, 0x4d, 0x12, 0xbe, 0xd5, 0x8c, 0x38, 0xda, 0x6f, 0x47, 0x86, 0x7d,
	0x68, 0x99, 0xf7, 0xc4, 0x17, 0xf7, 0xba, 0x76, 0x87, 0x15, 0x45, 0xf8, 0x29, 0xd4, 0x29, 0x03,
	0xd1, 0x75, 0xfb, 0x4e, 0xde, 0x3a, 0xd5, 0x00, 0xb6, 0xd1, 0xe0, 0x19, 0xb8, 0xab, 0x44, 0x92,
	0xe8, 0xd6, 0xb4, 0x49, 0x43, 0xef, 0x5f, 0x22, 0xd5, 0xfa, 0x29, 0xb1, 0xf7, 0x23, 0x74, 0x76,
	0xea, 0x61, 0x24, 0x0f, 0x96, 0xd3, 0x85, 0xba, 0xc8, 0x06, 0x56, 0x57, 0xd3, 0x60, 0x9b, 0x27,
	0x9e, 0x42, 0x33, 0x26, 0x0a, 0xbe, 0xe7, 0x49, 0xf2, 0x41, 0x57, 0xd2, 0x60, 0x5b, 0x81, 0x1a,
	0xe7, 0xa7, 0x8c, 0x7e, 0x5a, 0x92, 0x90, 0x2a, 0xed, 0x47, 0xe9, 0xea, 0x43, 0x6b, 0xe6, 0xc7,
	0x41, 0x14, 0xf8, 0x92, 0x72, 0xc6, 0x8a, 0x22, 0x45, 0xda, 0xdc, 0x17, 0xb2, 0x4c, 0x5a, 0x51,
	0x86, 0x67, 0x00, 0x73, 0x5f, 0xdc, 0x24, 0xe1, 0xad, 0x8a, 0x9f, 0x71, 0x56, 0x90, 0xe0, 0x6b,
	0x70, 0x53, 0x8d, 0x33, 0x23, 0xec, 0x7f, 0x8a, 0x8d, 0x1b, 0xdd, 0x95, 0xd1, 0xbd, 0x1f, 0x87,
	0xa4, 0x31, 0xb3, 0xcc, 0xc6, 0x4b, 0xe1, 0xa8, 0x80, 0xfc, 0x63, 0xc4, 0xf4, 0xa1, 0xa5, 0x98,
	0xbc, 0xe2, 0x7e, 0x2c, 0x29, 0x30, 0xe4, 0x14, 0x45, 0x78, 0x0e, 0xa0, 0x06, 0x88, 0x02, 0x15,
	0xc6, 0x4c, 0xd8, 0xb6, 0x0f, 0x05, 0x9d, 0x77, 0x0f, 0xcf, 0xf6, 0xd0, 0xfc, 0x37, 0x73, 0x7c,
	0x0b, 0x27, 0xa5, 0xb6, 0xe7, 0x93, 0xbc, 0x97, 0xec, 0xf0, 0xe2, 0x22, 0x54, 0xef, 0xd5, 0x60,
	0x66, 0x6d, 0xd0, 0xdf, 0x9e, 0x0f, 0xcd, 0x3c, 0x1b, 0xb6, 0xc1, 0xe2, 0x86, 0x29, 0x8b, 0xab,
	0x97, 0x30, 0x01, 0x2c, 0xa1, 0x96, 0x43, 0x61, 0x99, 0x6c, 0x02, 0xb4, 0x59, 0xfe, 0x56, 0xf3,
	0x94, 0x2e, 0xef, 0xe6, 0xd1, 0xec, 0x9a, 0xd6, 0xba, 0x85, 0x6d, 0xb6, 0x15, 0x78, 0xdf, 0xc1,
	0xd3, 0xd2, 0xee, 0xe3, 0x11, 0xd8, 0x51, 0x60, 0x10, 0xdb, 0x51, 0xb0, 0x4b, 0x84, 0xfd, 0x0f,
	0x44, 0xd4, 0xd4, 0xb5, 0x88, 0x82, 0x8b, 0x0b, 0xb0, 0xdf, 0xa5, 0x58, 0x07, 0xe7, 0x6a, 0x7c,
	0xdb, 0xa9, 0xa8, 0x8f, 0xe9, 0xf8, 0xb6, 0x63, 0x61, 0x13, 0xdc, 0xd1, 0xcd, 0x78, 0xc8, 0x3a,
	0xb6, 0x92, 0x8d, 0x86, 0xd3, 0x8e, 0x33, 0xf8, 0xdd, 0x82, 0xfa, 0xf5, 0x6a, 0x2a, 0x13, 0x4e,
	0x78, 0x0a, 0xce, 0x15, 0x49, 0xdc, 0x9c, 0xdd, 0x1e, 0x64, 0xbf, 0x0f, 0xfa, 0x94, 0x57, 0xf0,
	0x15, 0x38, 0x53, 0x92, 0xb8, 0x73, 0x77, 0x4b, 0x26, 0x7d, 0x70, 0x47, 0xfa, 0xc8, 0x6e, 0x0f,
	0x6f, 0xc9, 0xe2, 0xa5, 0xce, 0x8b, 0x85, 0xbb, 0xbb, 0x6b, 0x30, 0xf8, 0xcb, 0x82, 0x2a, 0xf3,
	0x3f, 0x48, 0xfc, 0x1a, 0x9e, 0xec, 0x74, 0x15, 0xf5, 0x80, 0xef, 0xdd, 0xab, 0xde, 0xc9, 0x9e,
	0x98, 0x91, 0xca, 0xf4, 0x25, 0xb4, 0x0a, 0x13, 0x8f, 0xc7, 0x59, 0x96, 0x9d, 0xe5, 0xed, 0x61,
	0x49, 0xb8, 0xf1, 0x3c, 0x36, 0xb2, 0xe2, 0x00, 0xe3, 0xe1, 0x05, 0xeb, 0x99, 0xe9, 0x8f, 0x02,
	0xed, 0x59, 0x3e, 0x40, 0x02, 0xbb, 0x07, 0xf0, 0x65, 0xc8, 0x0b, 0x9e, 0x77, 0x35, 0xfd, 0x2f,
	0xec, 0x8b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x29, 0xf9, 0xf2, 0x91, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvStoreClient is the client API for KvStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvStoreClient interface {
	// Get the value associated with a key.
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error)
	Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Result, error)
	Clear(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error)
	CAS(ctx context.Context, in *CASArg, opts ...grpc.CallOption) (*Result, error)
}

type kvStoreClient struct {
	cc *grpc.ClientConn
}

func NewKvStoreClient(cc *grpc.ClientConn) KvStoreClient {
	return &kvStoreClient{cc}
}

func (c *kvStoreClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) Set(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) Clear(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/Clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvStoreClient) CAS(ctx context.Context, in *CASArg, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/pb.KvStore/CAS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvStoreServer is the server API for KvStore service.
type KvStoreServer interface {
	// Get the value associated with a key.
	Get(context.Context, *Key) (*Result, error)
	Set(context.Context, *KeyValue) (*Result, error)
	Clear(context.Context, *Empty) (*Result, error)
	CAS(context.Context, *CASArg) (*Result, error)
}

func RegisterKvStoreServer(s *grpc.Server, srv KvStoreServer) {
	s.RegisterService(&_KvStore_serviceDesc, srv)
}

func _KvStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Set(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).Clear(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvStore_CAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CASArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvStoreServer).CAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.KvStore/CAS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvStoreServer).CAS(ctx, req.(*CASArg))
	}
	return interceptor(ctx, in, info, handler)
}

var _KvStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KvStore",
	HandlerType: (*KvStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KvStore_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KvStore_Set_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _KvStore_Clear_Handler,
		},
		{
			MethodName: "CAS",
			Handler:    _KvStore_CAS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesRet, error)
	RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteRet, error)
	RequestLeaderChange(ctx context.Context, in *LeaderChangeProof, opts ...grpc.CallOption) (*Void, error)
	AppendEntriesRes(ctx context.Context, in *AppendEntriesResArgs, opts ...grpc.CallOption) (*Void, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesArgs, opts ...grpc.CallOption) (*AppendEntriesRet, error) {
	out := new(AppendEntriesRet)
	err := c.cc.Invoke(ctx, "/pb.Raft/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteRet, error) {
	out := new(RequestVoteRet)
	err := c.cc.Invoke(ctx, "/pb.Raft/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) RequestLeaderChange(ctx context.Context, in *LeaderChangeProof, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/pb.Raft/RequestLeaderChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntriesRes(ctx context.Context, in *AppendEntriesResArgs, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/pb.Raft/AppendEntriesRes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	AppendEntries(context.Context, *AppendEntriesArgs) (*AppendEntriesRet, error)
	RequestVote(context.Context, *RequestVoteArgs) (*RequestVoteRet, error)
	RequestLeaderChange(context.Context, *LeaderChangeProof) (*Void, error)
	AppendEntriesRes(context.Context, *AppendEntriesResArgs) (*Void, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_RequestLeaderChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderChangeProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestLeaderChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/RequestLeaderChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestLeaderChange(ctx, req.(*LeaderChangeProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntriesRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesResArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntriesRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Raft/AppendEntriesRes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntriesRes(ctx, req.(*AppendEntriesResArgs))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "RequestLeaderChange",
			Handler:    _Raft_RequestLeaderChange_Handler,
		},
		{
			MethodName: "AppendEntriesRes",
			Handler:    _Raft_AppendEntriesRes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv.proto",
}
